// Generated by CoffeeScript 1.12.1
(function() {
  var dup;

  dup = function(a, b) {
    return a + " nie jest " + b;
  };

  dup("kot", "pies");

}).call(this);

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaml6ZXJhLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiaml6ZXJhLmNvZmZlZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7QUFBQSxNQUFBOztFQUFBLEdBQUEsR0FBTSxTQUFDLENBQUQsRUFBRyxDQUFIO1dBQ0MsQ0FBRCxHQUFHLFlBQUgsR0FBZTtFQURmOztFQUdOLEdBQUEsQ0FBSSxLQUFKLEVBQVUsTUFBVjtBQUhBIiwic291cmNlc0NvbnRlbnQiOlsiZHVwID0gKGEsYikgLT5cbiAgICBcIiN7YX0gbmllIGplc3QgI3tifVwiXG5cbmR1cCBcImtvdFwiLFwicGllc1wiXG4iXX0=
//# sourceURL=/home/gronki/Code/jizera/ui/jizera.coffee
